services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    # Add a volume to persist your data
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com" # Change this to your email
      PGADMIN_DEFAULT_PASSWORD: "admin" # Change this to a secure password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: